- name: "feature"
  color: "0E8A16"
  description: "Feature PRs"
- name: "fix"
  color: "B60205"
  description: "Fix PRs"
- name: "test"
  color: "5319E7"
  description: "Tests PRs"
- name: "docs"
  color: "BFD4F2"
  description: "Docs PRs"
- name: "refactor"
  color: "FBCA04"
  description: "Refactor PRs"
- name: "ci"
  color: "E99695"
  description: "CI PRs"
- name: "major"
  color: "0E8A16"
  description: "Manor release version vX.y.z"
- name: "minor"
  color: "1D76DB"
  description: "Minor release version vx.Y.z"
- name: "patch"
  color: "B60205"
  description: "Patch release version vx.y.Z"
